services:
  subdock:
    container_name: subdock
    image: yuuuuu0/subdock:latest
    pull_policy: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - WEBSITE_TITLE=Subdock
      - JWT_SECRET=your_jwt_secret
    restart: always
